#!/usr/bin/env python3
"""Generate the weights of MySQL's utf8mb4_general_ci by asking MySQL for them.

The table is measured, not copied: no MySQL source code or source table is
read. For every code point of the Basic Multilingual Plane but the surrogates,
the script asks the pinned MySQL 8.4 server for

  HEX(WEIGHT_STRING(CONVERT(CHAR(n USING utf32) USING utf8mb4)
                    COLLATE utf8mb4_general_ci))

and keeps the answer. Each character has exactly one two-byte weight; the
script refuses an answer of any other length. It also asks for every code point
past the Basic Multilingual Plane and checks that each weighs 0xFFFD, the one
weight the engine gives them without a table.

The weights are written in pages of 256 code points. A page where every
character weighs its own code point is left out, so only the pages holding
another weight are written.

Run from the repository root, with Docker:
  python3 core/translate/generate_mysql_general_ci.py
which starts the pinned server in a container of its own and removes it, or
  python3 core/translate/generate_mysql_general_ci.py --container NAME
to ask a pinned server that is already running in container NAME.
"""

import argparse
import pathlib
import subprocess
import time
import uuid

IMAGE = "mysql@sha256:b3b90af2a6552ae30c266fdb7d5dd55f3afb72404bb78d37fe8a23eb857fd3fb"
PASSWORD = "oracle"
OUTPUT = pathlib.Path(__file__).with_name("mysql_general_ci_weights.rs")
PAST_THE_BMP = 0xFFFD

BMP_QUERY = """
SET SESSION cte_max_recursion_depth = 70000;
WITH RECURSIVE code_points (n) AS (
  SELECT 0 UNION ALL SELECT n + 1 FROM code_points WHERE n < 65535
)
SELECT n, HEX(WEIGHT_STRING(CONVERT(CHAR(n USING utf32) USING utf8mb4)
                            COLLATE utf8mb4_general_ci))
FROM code_points
WHERE n NOT BETWEEN 55296 AND 57343
ORDER BY n;
"""

PAST_THE_BMP_QUERY = """
SET SESSION cte_max_recursion_depth = 1200000;
WITH RECURSIVE code_points (n) AS (
  SELECT 65536 UNION ALL SELECT n + 1 FROM code_points WHERE n < 1114111
)
SELECT COUNT(*),
       SUM(HEX(WEIGHT_STRING(CONVERT(CHAR(n USING utf32) USING utf8mb4)
                             COLLATE utf8mb4_general_ci)) = 'FFFD')
FROM code_points;
"""


def ask(container: str, sql: str) -> list[list[str]]:
    answer = subprocess.run(
        [
            "docker", "exec", "-i", container, "mysql",
            "--default-character-set=utf8mb4", "-uroot", f"-p{PASSWORD}",
            "-N", "-B",
        ],
        input=sql, capture_output=True, text=True, check=True,
    )
    return [line.split("\t") for line in answer.stdout.splitlines()]


def start_server() -> str:
    container = f"general-ci-weights-{uuid.uuid4().hex[:8]}"
    subprocess.run(
        ["docker", "run", "-d", "--name", container,
         "-e", f"MYSQL_ROOT_PASSWORD={PASSWORD}", IMAGE],
        check=True, capture_output=True,
    )
    for _ in range(120):
        ping = subprocess.run(
            ["docker", "exec", container, "mysqladmin", "-uroot",
             f"-p{PASSWORD}", "ping"],
            capture_output=True, text=True,
        )
        if "alive" in ping.stdout:
            return container
        time.sleep(2)
    raise RuntimeError(f"{container} did not start")


def measure(container: str) -> dict[int, int]:
    version = ask(container, "SELECT VERSION();")[0][0]
    if not version.startswith("8.4."):
        raise ValueError(f"expected MySQL 8.4, the server is {version}")
    weights = {}
    for code_point, weight in ask(container, BMP_QUERY):
        if len(weight) != 4:
            raise ValueError(f"U+{int(code_point):04X} weighs {weight!r}, not one weight")
        weights[int(code_point)] = int(weight, 16)
    expected = 0x10000 - (0xE000 - 0xD800)
    if len(weights) != expected:
        raise ValueError(f"measured {len(weights)} code points, expected {expected}")
    [[count, weighing_fffd]] = ask(container, PAST_THE_BMP_QUERY)
    if count != weighing_fffd or int(count) != 0x100000:
        raise ValueError(
            f"{weighing_fffd} of {count} code points past the BMP weigh 0xFFFD"
        )
    return weights


def write_table(weights: dict[int, int], version: str) -> None:
    pages = []
    page_of = []
    for page in range(256):
        page_weights = [
            weights.get(code_point, code_point)
            for code_point in range(page * 256, page * 256 + 256)
        ]
        if page_weights == list(range(page * 256, page * 256 + 256)):
            page_of.append(0)
            continue
        pages.append(page_weights)
        page_of.append(len(pages))
    lines = [
        f"//! Generated by `generate_mysql_general_ci.py` from MySQL {version}'s",
        "//! `WEIGHT_STRING(... COLLATE utf8mb4_general_ci)` of every code point of the",
        "//! Basic Multilingual Plane. Do not edit; run the script again.",
        "",
        "/// For each page of 256 code points, its place in [`PAGES`] counted from 1,",
        "/// or 0 when every character of the page weighs its own code point.",
        "#[rustfmt::skip]",
        "pub(super) const PAGE_OF: [u8; 256] = [",
    ]
    for start in range(0, 256, 16):
        lines.append("    " + " ".join(f"{index}," for index in page_of[start:start + 16]))
    lines.append("];")
    lines.append("")
    lines.append("#[rustfmt::skip]")
    lines.append(f"pub(super) const PAGES: [[u16; 256]; {len(pages)}] = [")
    for page in pages:
        lines.append("    [")
        for start in range(0, 256, 8):
            lines.append(
                "        " + " ".join(f"0x{weight:04X}," for weight in page[start:start + 8])
            )
        lines.append("    ],")
    lines.append("];")
    OUTPUT.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--container", help="a running pinned MySQL 8.4 container")
    arguments = parser.parse_args()
    container = arguments.container or start_server()
    try:
        version = ask(container, "SELECT VERSION();")[0][0]
        weights = measure(container)
    finally:
        if not arguments.container:
            subprocess.run(["docker", "rm", "-f", container], capture_output=True)
    write_table(weights, version)
    print(f"wrote {OUTPUT} from MySQL {version}")


if __name__ == "__main__":
    main()
